### ISSUE TITLE
OrderedMethods do not work with custom DSLs

### ISSUE THREAD

**Issue by Darhazer** [shanecav84/rubocop-ordered_methods#10]
Memoization gems like memoist and memo_wise allows you to define memoized method with a DSL like
```
memo_wise def foo = some_expensive_calculation
```

It would be nice if those can still be ordered by the cop. Perhaps a configuration options for the custom method modifiers (like `memo_wise` in the example above) could be provided

**Comment by shanecav84** [comment]
I think we can make "[qualifiers](https://github.com/shanecav84/rubocop-ordered_methods/blob/f51059ae89922d65eea46f65c04d4bf156437e3e/lib/rubocop/cop/qualifier_node_matchers.rb#L9)" configurable, so people can add their own in addition to the standard ruby ones. Something like this in the `.rubocop.yml`:

```yml
Layout/OrderedMethods:
  Qualifiers: ['memo_wise']
```

**Comment by Darhazer** [comment]
I was under the impression that the qualifiers are used only during the auto-correction. E.g. would it trigger an offense for:
```
memo_wise def a; end
memo_wise def b; end
```
(or for that matter)
```
private_class_method :b
private_class_method :a
```

**Comment by shanecav84** [comment]
Ah, I was looking at the `memo_wise` docs which use 

```ruby
def some_def
...
end
memo_wise :some_def
```

So you can also do this?

```ruby
memo_wise def some_def
...
end
```

**Comment by Darhazer** [comment]
Yes, as `def` returns a symbol with the name of the defined method, so `memo_wise :some_def` and `memo_wise def some_def` is essentially the same from memo_wise point of view.

Though you are right, extending the Qualifiers will be useful for the `memo_wise :some_def` usage and should also be covered!

**Comment by shanecav84** [comment]
I see. So you want `memo_wise` to be supported as a qualifier AND for `memo_wise def some_def` to alphabetize as `some_def`?

**Comment by Darhazer** [comment]
Now that you mention it - yes. (My initial though was for the alphabetization, as that's my usage, but other users may use it as a qualifier, so thanks for mentioning it.)

**Comment by shanecav84** [comment]
The qualifier might be easy enough. I'll have to look into the possibility for ordering, though using the `memo_wise` as a qualifier might be as much as I can do.
