### ISSUE TITLE
Support for sorbet

### ISSUE THREAD

**Issue by jaredbeck** [shanecav84/rubocop-ordered_methods#3]
If you approve this change, I'll work on this one. This issue is just a reminder to myself.

Ruby 3 will have something like these signatures, but I'm not sure if the syntax has been decided yet.

## Input

```ruby
sig { returns(String) }
def b
  "one"
end

sig { returns(Integer) }
def a
  1
end
```

## Expected Output

```ruby
sig { returns(Integer) }
def a
  1
end

sig { returns(String) }
def b
  "one"
end
```

## Actual Output

```ruby
sig { returns(String) }
def a
  1
end

def b
  "one"
end

sig { returns(Integer) }
```

**Comment by shanecav84** [comment]
How about we give RBS a shot?

**Comment by jaredbeck** [comment]
> How about we give RBS a shot?

I'm willing to give it a try, though I think that, compared to `sig`, managing a separate RBS file will not be ergonomic. 

It looks like there are RBS-only type-checkers in development (https://github.com/soutaro/steep) though, at first glance, I think they have a long way to go to catch up with the features of Sorbet.

Jake Zimmerman says that Sorbet will eventually support RBS. (https://github.com/sorbet/sorbet/blob/e68d30e04a493feda5be59d06db0d8ca618f98c9/website/blog/2020-07-30-ruby-3-rbs-sorbet.md) So, if/when that happens, we could also try using Sorbet without `sig`.
